### ISSUE TITLE
Can I have a simploest example of creating issue using this rep?

### ISSUE THREAD

**Issue by iamarsenibragimov** [devmoath/jira-php#8]
I tried a lot but it says project id or key is missing or wrong

**Comment by devmoath** [comment]
Here an example how to use the api with this package: https://github.com/devmoath/jira-php#create-function-2
For the body content refers to Jira apis docs: https://docs.atlassian.com/software/jira/docs/api/REST/8.0.0/#api/2/issue-createIssue
